/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    subscribers: Subscriber;
    media: Media;
    'newsletter-lists': NewsletterList;
    'newsletter-campaigns': NewsletterCampaign;
    'newsletter-sync-runs': NewsletterSyncRun;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'newsletter-lists': NewsletterListsSelect<false> | NewsletterListsSelect<true>;
    'newsletter-campaigns': NewsletterCampaignsSelect<false> | NewsletterCampaignsSelect<true>;
    'newsletter-sync-runs': NewsletterSyncRunsSelect<false> | NewsletterSyncRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'newsletter-settings': NewsletterSetting;
  };
  globalsSelect: {
    'newsletter-settings': NewsletterSettingsSelect<false> | NewsletterSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Receives newsletters. Unsubscribing from an email turns this off automatically.
   */
  subscribed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  plan?: ('free' | 'pro') | null;
  company?: string | null;
  /**
   * Receives newsletters. Unsubscribing from an email turns this off automatically.
   */
  subscribed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Each list is a Resend segment built from one collection. Membership follows the documents: saving, filtering or deleting them updates the segment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-lists".
 */
export interface NewsletterList {
  id: number;
  name: string;
  description?: string | null;
  /**
   * The collection whose documents are the subscribers of this list.
   */
  source: 'users' | 'subscribers';
  /**
   * Optional Payload query that narrows the source, e.g. {"plan": {"equals": "pro"}}. Empty means everyone in the collection. Unsubscribed documents may match; Resend never mails them.
   */
  filter?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  segmentId?: string | null;
  /**
   * Subscribed members at the last sync.
   */
  memberCount?: number | null;
  lastSyncedAt?: string | null;
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletters sent through Resend Broadcasts. Write the copy here, then open Preview & send to see it as any subscriber, send a test, and send or schedule it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-campaigns".
 */
export interface NewsletterCampaign {
  id: number;
  /**
   * Internal name, also shown on the broadcast in Resend.
   */
  name: string;
  /**
   * Who receives it: every subscribed contact in this list’s Resend segment.
   */
  list: number | NewsletterList;
  /**
   * Values the same for everyone, like {{site.name}}, can be used here. Per-subscriber ones cannot.
   */
  subject: string;
  /**
   * The line inbox lists show after the subject.
   */
  previewText?: string | null;
  /**
   * Use {{firstName}}, {{name|there}} and the other variables listed on Preview & send. A fallback after | is used when a subscriber has no value.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'scheduled' | 'sending' | 'sent' | 'failed') | null;
  /**
   * Overrides Newsletter Settings, e.g. "Ada from Acme <news@acme.com>". Must be on a domain verified in Resend.
   */
  from?: string | null;
  replyTo?: string | null;
  scheduledAt?: string | null;
  sentAt?: string | null;
  broadcastId?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every reconciliation with Resend: full resyncs, and the ones that fill a list after it is created or refiltered.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-sync-runs".
 */
export interface NewsletterSyncRun {
  id: number;
  status: 'running' | 'finished' | 'failed';
  scope?: ('all' | 'list') | null;
  lists?: string[] | null;
  trigger?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'newsletter-lists';
        value: number | NewsletterList;
      } | null)
    | ({
        relationTo: 'newsletter-campaigns';
        value: number | NewsletterCampaign;
      } | null)
    | ({
        relationTo: 'newsletter-sync-runs';
        value: number | NewsletterSyncRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  subscribed?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  plan?: T;
  company?: T;
  subscribed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-lists_select".
 */
export interface NewsletterListsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  source?: T;
  filter?: T;
  segmentId?: T;
  memberCount?: T;
  lastSyncedAt?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-campaigns_select".
 */
export interface NewsletterCampaignsSelect<T extends boolean = true> {
  name?: T;
  list?: T;
  subject?: T;
  previewText?: T;
  body?: T;
  status?: T;
  from?: T;
  replyTo?: T;
  scheduledAt?: T;
  sentAt?: T;
  broadcastId?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-sync-runs_select".
 */
export interface NewsletterSyncRunsSelect<T extends boolean = true> {
  status?: T;
  scope?: T;
  lists?: T;
  trigger?: T;
  startedAt?: T;
  finishedAt?: T;
  stats?: T;
  errors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-settings".
 */
export interface NewsletterSetting {
  id: number;
  /**
   * "Name <address>" on a domain verified in Resend. Empty uses Acme Weekly <news@acme.test>.
   */
  from?: string | null;
  replyTo?: string | null;
  /**
   * Shown above every campaign by the default template; {{site.name}}.
   */
  siteName?: string | null;
  /**
   * {{site.url}}. Defaults to the server URL.
   */
  siteUrl?: string | null;
  /**
   * Under every campaign: who you are and why the reader gets this. The unsubscribe link is added below it automatically.
   */
  footer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  unsubscribeLabel?: string | null;
  /**
   * Default address for test sends. Empty uses your own.
   */
  testRecipient?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-settings_select".
 */
export interface NewsletterSettingsSelect<T extends boolean = true> {
  from?: T;
  replyTo?: T;
  siteName?: T;
  siteUrl?: T;
  footer?: T;
  unsubscribeLabel?: T;
  testRecipient?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailButtonBlock".
 */
export interface EmailButtonBlock {
  label: string;
  /**
   * A full URL, or a variable such as {{site.url}}.
   */
  url: string;
  align?: ('left' | 'center') | null;
  /**
   * Repeats the URL as plain text under the button, in smaller type. Some clients strip links, and some readers forward the message as text.
   */
  fallback?: boolean | null;
  /**
   * Leave empty to show the link on its own.
   */
  fallbackText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterImageBlock".
 */
export interface NewsletterImageBlock {
  image: number | Media;
  /**
   * Read aloud by screen readers and shown when a mail client blocks images. Empty uses the alt text of the upload.
   */
  alt?: string | null;
  width: 'full' | 'half' | 'third';
  align?: ('left' | 'center') | null;
  /**
   * Optional. Clicking the image opens this URL; variables such as {{site.url}} work.
   */
  href?: string | null;
  /**
   * Optional small print under the image.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}