import type { CollectionConfig } from 'payload'

/**
 * Organizations are the tenants of the app. The collection is generated by payload-auth from the
 * Better Auth organization plugin (name, slug, logo, metadata, members, invitations); fields declared
 * here are merged in. The multi-tenant plugin points at this collection as `tenantsSlug`.
 */
export const Organizations: CollectionConfig = {
  slug: 'organizations',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'slug', 'createdAt'],
  },
  fields: [
    {
      name: 'onboardedAt',
      type: 'date',
      admin: { position: 'sidebar', description: 'Set when the organization finished onboarding.' },
    },
  ],
}
