/**
 * Consumer-side typing check. `payload-types.ts` (generated by poc.ts) augments `GeneratedTypes`;
 * the plugin's public types below derive everything from it. Compiled with `tsc --noEmit`.
 */
import type { BasePayload, GeneratedTypes, Payload, PayloadRequest } from 'payload'
import './payload-types.generated.js'

// ---------- what the plugin package exports (src/types.ts) ----------

type EmailShape = { input: unknown; variables: unknown }
type UntypedEmails = Record<string, { input: Record<string, unknown>; variables: Record<string, unknown> }>

export type TypedEmails = GeneratedTypes extends { emails: infer E extends Record<string, EmailShape> }
  ? E
  : UntypedEmails

export type EmailSlug = keyof TypedEmails & string
export type EmailInput<S extends EmailSlug> = TypedEmails[S]['input']
export type EmailVariables<S extends EmailSlug> = TypedEmails[S]['variables']

export type ResolveArgs<S extends EmailSlug> = {
  input: EmailInput<S>
  locale?: string
  payload: Payload
  req?: PayloadRequest
}

export type EmailDefinition<S extends EmailSlug = EmailSlug> = {
  slug: S
  label: string
  resolve?: (args: ResolveArgs<S>) => EmailVariables<S> | Promise<EmailVariables<S>>
  to?: (args: { input: EmailInput<S>; variables: EmailVariables<S> }) => string | string[]
}

export function defineEmail<S extends EmailSlug>(def: EmailDefinition<S>): EmailDefinition<S> {
  return def
}

export type SendArgs<S extends EmailSlug> = {
  input: EmailInput<S>
  locale?: string
  to?: string | string[]
  queue?: boolean
}

export type SendResult = { status: 'failed' | 'queued' | 'sent' | 'skipped'; reason?: string }

export interface EmailsAPI {
  render<S extends EmailSlug>(slug: S, args: SendArgs<S>): Promise<{ html: string; subject: string; text: string }>
  send<S extends EmailSlug>(slug: S, args: SendArgs<S>): Promise<SendResult>
}

// Module augmentation: interface merges into the exported `BasePayload` class instance type.
declare module 'payload' {
  interface BasePayload {
    emails: EmailsAPI
  }
}

// ---------- what a project would write ----------

export const welcome = defineEmail({
  slug: 'welcome',
  label: 'Welcome',
  resolve: ({ input }) => ({
    // input.user is `string | User`, input.url is `string` — both from payload-types.ts
    'user.name': typeof input.user === 'string' ? input.user : (input.user.name ?? input.user.email),
    'user.email': typeof input.user === 'string' ? input.user : input.user.email,
    url: input.url,
  }),
  to: ({ variables }) => variables['user.email'],
})

export const invitation = defineEmail({
  slug: 'organization-invitation',
  label: 'Organization invitation',
  resolve: ({ input }) => ({
    'organization.name': input.organizationName,
    'inviter.name': typeof input.inviter === 'object' && input.inviter ? (input.inviter.name ?? '') : '',
    role: input.role ?? 'member',
    url: input.url,
    'expires.hours': input.expiresInHours ?? 48,
  }),
})

export async function usage(payload: BasePayload, userId: string) {
  // OK: slug autocompletes, input is typed
  await payload.emails.send('welcome', { input: { user: userId, url: 'https://example.com/verify' } })
  await payload.emails.send('organization-invitation', {
    input: { organizationName: 'Fortbit', url: 'https://example.com/i/abc', role: 'admin' },
    locale: 'en',
  })

  // @ts-expect-error unknown slug
  await payload.emails.send('welcom', { input: {} })

  // @ts-expect-error missing required `url`
  await payload.emails.send('welcome', { input: { user: userId } })

  // @ts-expect-error `role` is a select: only 'member' | 'admin'
  await payload.emails.send('organization-invitation', { input: { organizationName: 'x', url: 'y', role: 'owner' } })
}

// @ts-expect-error resolve must return every declared variable ('url' missing)
export const broken = defineEmail({ slug: 'welcome', label: 'x', resolve: () => ({ 'user.name': 'a', 'user.email': 'b' }) })
