/**
 * Proof of concept: typed email definitions via Payload's `typescript.schema` hook.
 * Runs Payload's real `generateTypes` against a minimal config with a fake DB adapter.
 */
import type { Config, Field, JSONSchema4Like } from 'payload'
import { buildConfig, fieldsToJSONSchema, flattenAllFields } from 'payload'
import { generateTypes } from 'payload/node'
import type { JSONSchema4 } from 'json-schema'

// ---- what the plugin would receive ------------------------------------------------------------

type VariableSpec = { description?: string; example?: string; type?: 'string' | 'number' | 'date' | 'url' | 'html' }

type EmailDefinition = {
  slug: string
  label: string
  inputSchema?: Field[]
  variables?: Record<string, VariableSpec>
  interfaceName?: string
}

const emails: EmailDefinition[] = [
  {
    slug: 'welcome',
    label: 'Welcome',
    inputSchema: [
      { name: 'user', type: 'relationship', relationTo: 'users', required: true },
      { name: 'url', type: 'text', required: true },
    ],
    variables: {
      'user.name': { description: 'Display name', example: 'Ada Lovelace' },
      'user.email': { example: 'ada@example.com' },
      url: { type: 'url', example: 'https://example.com/verify?token=…' },
    },
  },
  {
    slug: 'organization-invitation',
    label: 'Organization invitation',
    inputSchema: [
      { name: 'organizationName', type: 'text', required: true },
      { name: 'inviter', type: 'relationship', relationTo: 'users' },
      { name: 'role', type: 'select', options: ['member', 'admin'] },
      { name: 'url', type: 'text', required: true },
      { name: 'expiresInHours', type: 'number', defaultValue: 48 },
    ],
    variables: {
      'organization.name': {},
      'inviter.name': {},
      role: {},
      url: { type: 'url' },
      'expires.hours': { type: 'number' },
    },
  },
]

// ---- the plugin's typescript.schema hook ------------------------------------------------------

const pascal = (s: string) => s.replace(/(^|[-_ ])(\w)/g, (_, __, c: string) => c.toUpperCase())

const emailsTypeScriptSchema: NonNullable<NonNullable<Config['typescript']>['schema']>[number] = ({
  collectionIDFieldTypes,
  config,
  i18n,
  jsonSchema,
}) => {
  const definitions = new Map<string, JSONSchema4>()
  const properties: Record<string, JSONSchema4> = {}

  for (const email of emails) {
    const interfaceName = email.interfaceName ?? `Email${pascal(email.slug)}`

    const input = fieldsToJSONSchema(
      collectionIDFieldTypes,
      flattenAllFields({ fields: email.inputSchema ?? [] }),
      definitions,
      config,
      i18n,
    )

    const variables: JSONSchema4 = {
      type: 'object',
      additionalProperties: false,
      properties: Object.fromEntries(
        Object.entries(email.variables ?? {}).map(([name, spec]) => [
          name,
          {
            type: spec.type === 'number' ? 'number' : 'string',
            ...(spec.description ? { description: spec.description } : {}),
          },
        ]),
      ),
      required: Object.keys(email.variables ?? {}),
    }

    definitions.set(interfaceName, {
      type: 'object',
      additionalProperties: false,
      properties: {
        input: { type: 'object', additionalProperties: false, properties: input.properties, required: input.required },
        variables,
      },
      required: ['input', 'variables'],
    })
    properties[email.slug] = { $ref: `#/definitions/${interfaceName}` }
  }

  jsonSchema.definitions = { ...jsonSchema.definitions, ...Object.fromEntries(definitions) }
  jsonSchema.properties = {
    ...jsonSchema.properties,
    emails: {
      type: 'object',
      additionalProperties: false,
      description: 'Generated by @payload-solutions/plugin-emails',
      properties,
      required: Object.keys(properties),
    },
  }
  if (Array.isArray(jsonSchema.required)) jsonSchema.required.push('emails')
  return jsonSchema
}

// ---- minimal host config --------------------------------------------------------------------

const fakeDb = { defaultIDType: 'text', init: () => ({}) } as unknown as Config['db']

const config = await buildConfig({
  secret: 'poc',
  db: fakeDb,
  collections: [
    {
      slug: 'users',
      auth: true,
      fields: [{ name: 'name', type: 'text' }],
    },
  ],
  typescript: { outputFile: new URL('./payload-types.ts', import.meta.url).pathname, schema: [emailsTypeScriptSchema] },
})

await generateTypes(config)
