import type { JSONSchema4 } from 'json-schema'
import type { Config } from 'payload'

import { fieldsToJSONSchema, flattenAllFields } from 'payload'

import type { SanitizedEmailsPluginOptions, VariableSpec } from '../types.js'

type SchemaHook = NonNullable<NonNullable<Config['typescript']>['schema']>[number]

function variableSchema(spec: VariableSpec): JSONSchema4 {
  const base: JSONSchema4 = spec.description ? { description: spec.description } : {}
  switch (spec.type) {
    case 'date':
      // json-schema-to-typescript honours `tsType`; resolvers may return a Date or an ISO string.
      return { ...base, tsType: 'Date | string' } as JSONSchema4
    case 'number':
      return { ...base, type: 'number' }
    default:
      return { ...base, type: 'string' }
  }
}

/**
 * Adds `Config['emails']` to the generated types: one `Email<PascalSlug>` interface per definition
 * with `input` (from `inputSchema`, like jobs tasks) and `variables` (from the manifest).
 */
export function createEmailsTypeScriptSchema(options: SanitizedEmailsPluginOptions): SchemaHook {
  return ({ collectionIDFieldTypes, config, i18n, jsonSchema }) => {
    const definitions = new Map<string, JSONSchema4>()
    const properties: Record<string, JSONSchema4> = {}

    for (const definition of options.definitions.values()) {
      const input = fieldsToJSONSchema(
        collectionIDFieldTypes,
        flattenAllFields({ fields: definition.inputSchema ?? [] }),
        definitions,
        config,
        i18n,
      )
      const variables: JSONSchema4 = {
        type: 'object',
        additionalProperties: false,
        properties: Object.fromEntries(
          Object.entries(definition.variables).map(([name, spec]) => [name, variableSchema(spec)]),
        ),
        required: Object.keys(definition.variables),
      }
      definitions.set(definition.interfaceName, {
        type: 'object',
        additionalProperties: false,
        description: `Generated by @payload-solutions/plugin-emails for "${definition.slug}"`,
        properties: {
          input: {
            type: 'object',
            additionalProperties: false,
            properties: input.properties ?? {},
            required: input.required ?? [],
          },
          variables,
        },
        required: ['input', 'variables'],
      })
      properties[definition.slug] = { $ref: `#/definitions/${definition.interfaceName}` }
    }

    jsonSchema.definitions = { ...jsonSchema.definitions, ...Object.fromEntries(definitions) }
    jsonSchema.properties = {
      ...jsonSchema.properties,
      emails: {
        type: 'object',
        additionalProperties: false,
        description: 'Generated by @payload-solutions/plugin-emails',
        properties,
        required: Object.keys(properties),
      },
    }
    if (Array.isArray(jsonSchema.required) && !jsonSchema.required.includes('emails')) {
      jsonSchema.required.push('emails')
    }
    return jsonSchema
  }
}
