/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'transactional-emails': TransactionalEmail;
    'email-log': EmailLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'transactional-emails': TransactionalEmailsSelect<false> | TransactionalEmailsSelect<true>;
    'email-log': EmailLogSelect<false> | EmailLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'email-settings': EmailSetting;
  };
  globalsSelect: {
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by @payload-solutions/plugin-emails
   */
  emails: {
    welcome: EmailWelcome;
    'password-reset': EmailPasswordReset;
    'new-user-notification': EmailNewUserNotification;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Subject and body of every automated email. Variables such as {{user.name}} are filled in when the email is sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactional-emails".
 */
export interface TransactionalEmail {
  id: number;
  subject: string;
  /**
   * Preview text shown next to the subject in most inboxes.
   */
  preheader?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  recipients?: {
    /**
     * Recipients of this email. Leave empty to use the defaults from email settings.
     */
    to?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    cc?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    bcc?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    replyTo?: string | null;
  };
  /**
   * Input used by the preview and by test sends. Leave empty to use the sample defined in code.
   */
  sampleInput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Required emails (password reset, verification) are always sent and cannot be disabled.
   */
  enabled?: boolean | null;
  key: string;
  label?: string | null;
  description?: string | null;
  trigger?: string | null;
  group?: string | null;
  audience?: ('user' | 'admin' | 'custom') | null;
  required?: boolean | null;
  inUse?: boolean | null;
  variables?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  definitionHash?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every send attempt. Rows older than the retention period are purged.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log".
 */
export interface EmailLog {
  id: number;
  key: string;
  status: 'sent' | 'failed' | 'skipped' | 'queued';
  to?: string | null;
  cc?: string | null;
  bcc?: string | null;
  subject?: string | null;
  reason?: string | null;
  error?: string | null;
  messageId?: string | null;
  locale?: string | null;
  isTest?: boolean | null;
  durationMs?: number | null;
  sentAt: string;
  variables?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'transactional-emails';
        value: number | TransactionalEmail;
      } | null)
    | ({
        relationTo: 'email-log';
        value: number | EmailLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactional-emails_select".
 */
export interface TransactionalEmailsSelect<T extends boolean = true> {
  subject?: T;
  preheader?: T;
  body?: T;
  recipients?:
    | T
    | {
        to?:
          | T
          | {
              email?: T;
              id?: T;
            };
        cc?:
          | T
          | {
              email?: T;
              id?: T;
            };
        bcc?:
          | T
          | {
              email?: T;
              id?: T;
            };
        replyTo?: T;
      };
  sampleInput?: T;
  enabled?: T;
  key?: T;
  label?: T;
  description?: T;
  trigger?: T;
  group?: T;
  audience?: T;
  required?: T;
  inUse?: T;
  variables?: T;
  definitionHash?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log_select".
 */
export interface EmailLogSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  to?: T;
  cc?: T;
  bcc?: T;
  subject?: T;
  reason?: T;
  error?: T;
  messageId?: T;
  locale?: T;
  isTest?: T;
  durationMs?: T;
  sentAt?: T;
  variables?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Applies to every automated email. The design itself comes from the template.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Defaults to the address configured on the email adapter.
   */
  from?: {
    name?: string | null;
    address?: string | null;
  };
  replyTo?: string | null;
  /**
   * Who receives emails addressed to administrators.
   */
  adminRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Prefilled in the "Send test" field of every email.
   */
  testRecipient?: string | null;
  /**
   * Available in every email as {{site.name}}.
   */
  siteName?: string | null;
  /**
   * Available in every email as {{site.url}}. Defaults to the server URL.
   */
  siteUrl?: string | null;
  /**
   * Shown under the body of every email — company address, an unsubscribe note, a legal line.
   */
  footer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  from?:
    | T
    | {
        name?: T;
        address?: T;
      };
  replyTo?: T;
  adminRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  testRecipient?: T;
  siteName?: T;
  siteUrl?: T;
  footer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * Generated by @payload-solutions/plugin-emails for "welcome"
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailWelcome".
 */
export interface EmailWelcome {
  input: {
    user: number | User;
    /**
     * Where the button points
     */
    url: string;
  };
  variables: {
    /**
     * Display name, falls back to the email
     */
    'user.name': string;
    'user.email': string;
    url: string;
  };
}
/**
 * Generated by @payload-solutions/plugin-emails for "password-reset"
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailPasswordReset".
 */
export interface EmailPasswordReset {
  input: {
    email: string;
    url: string;
    expiresInMinutes?: number | null;
  };
  variables: {
    email: string;
    url: string;
    'expires.minutes': number;
  };
}
/**
 * Generated by @payload-solutions/plugin-emails for "new-user-notification"
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailNewUserNotification".
 */
export interface EmailNewUserNotification {
  input: {
    user: number | User;
    registeredAt: string;
  };
  variables: {
    'user.name': string;
    'user.email': string;
    /**
     * Admin link to the user
     */
    'user.link': string;
    registeredAt: Date | string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailButtonBlock".
 */
export interface EmailButtonBlock {
  label: string;
  /**
   * A full URL or a variable such as {{url}}.
   */
  url: string;
  align?: ('left' | 'center') | null;
  /**
   * Repeats the URL as plain text under the button, in smaller type. Some clients strip links, and some readers forward the message as text.
   */
  fallback?: boolean | null;
  /**
   * Leave empty to show the link on its own.
   */
  fallbackText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}