import type { Access, Field, GeneratedTypes, Payload, PayloadRequest } from 'payload'

/** `'30s' | '15m' | '2h' | '7d'` or a number of seconds. */
export type Duration = `${number}${'d' | 'h' | 'm' | 's'}` | number

export type ActionShape = { input: Record<string, unknown> }

/**
 * Generated by the plugin's `typescript.schema` hook as `Config['scheduledActions']`.
 * Before the first `generate:types` every hook is a string and every args object is loose.
 */
export type TypedActions = GeneratedTypes extends {
  scheduledActions: infer A extends Record<string, ActionShape>
}
  ? A
  : Record<string, ActionShape>

export type ActionSlug = keyof TypedActions & string

export type ActionArgs<S extends string = string> = S extends keyof TypedActions
  ? TypedActions[S]['input']
  : Record<string, unknown>

export type ActionStatus = 'canceled' | 'complete' | 'failed' | 'pending' | 'running'
export type ActionRepeat = 'cron' | 'interval' | 'once'
export type ActionOutcome = 'completed' | 'failed' | 'lost' | 'skipped' | 'timeout'
export type FailureReason =
  | 'args-invalid'
  | 'error'
  | 'handler-missing'
  | 'lost'
  | 'permanent'
  | 'timeout'
export type ActionSource = 'admin' | 'code' | 'series'
export type LogEvent =
  | 'canceled'
  | 'completed'
  | 'dispatched'
  | 'failed'
  | 'lost'
  | 'note'
  | 'rearmed'
  | 'rescheduled'
  | 'retry'
  | 'scheduled'
  | 'skipped'
  | 'started'
  | 'timeout'
export type LogLevel = 'error' | 'info' | 'warn'

export type Backoff =
  | ((attempt: number, error: unknown) => Date | null)
  | { base?: Duration; max?: Duration; type: 'exponential' }
  | { delay: Duration; type: 'fixed' }

export type ActionContext = {
  attempt: number
  group: string
  hook: string
  id: number | string
  maxAttempts: number
  recurring: boolean
  runCount: number
  scheduleAt: Date
}

export type ActionLogFn = (message: string, level?: LogLevel) => void

export type ActionHandlerArgs<TArgs = Record<string, unknown>> = {
  action: ActionContext
  args: TArgs
  log: ActionLogFn
  payload: Payload
  req: PayloadRequest
  signal: AbortSignal
}

export type ActionHandlerResult = { note?: string } | undefined | void

export type ActionHandler<TArgs = Record<string, unknown>> = (
  args: ActionHandlerArgs<TArgs>,
) => ActionHandlerResult | Promise<ActionHandlerResult>

export type ActionDefinition<TArgs = Record<string, unknown>> = {
  backoff?: Backoff
  description?: string
  /** Default group for this hook; callers may override per action. */
  group?: string
  handler: ActionHandler<TArgs>
  /** Payload fields describing `args`; drives type generation and the admin form. */
  inputSchema?: Field[]
  label?: string
  /** 0–255, lower runs first. Default 10. */
  priority?: number
  /** Payload queue the transport job is placed on. Default 'default'. */
  queue?: string
  /** Delete the row as soon as it completes instead of keeping it for retention. */
  retain?: boolean
  /** Attempts after the first one. Default 3 (`defaultRetries`). 0 = fail on the first error. */
  retries?: number
  /** `/^[a-z0-9]+([.-][a-z0-9]+)*$/` */
  slug: string
  /** Recurring only: give up after this many occurrences in a row ended failed. Default null = never. */
  stopAfterFailures?: null | number
  timeout?: Duration
  /** Skip scheduling when an identical pending/running action exists. Default false; recurring/cron default true. */
  unique?: boolean
}

export type ScheduledAction = {
  args: Record<string, unknown>
  argsHash: string
  attempts: number
  claimedUntil?: null | string
  claimToken?: null | string
  completedAt?: null | string
  consecutiveFailures: number
  createdAt: string
  createdBy?: null | string
  cron?: null | string
  errorMessage?: null | string
  errorStack?: null | string
  failureReason?: FailureReason | null
  group: string
  hook: string
  id: number | string
  interval?: null | number
  jobId?: null | string
  lastAttemptAt?: null | string
  lastDurationMs?: null | number
  lastOutcome?: ActionOutcome | null
  maxAttempts: number
  note?: null | string
  priority: number
  queue: string
  repeat: ActionRepeat
  runCount: number
  scheduleAt: string
  seriesKey?: null | string
  source: ActionSource
  status: ActionStatus
  stopAfterCurrent?: boolean | null
  tz?: null | string
  unique?: boolean | null
  uniqueKey?: null | string
  updatedAt: string
}

export type ScheduledActionLog = {
  action: number | string
  attempt?: null | number
  createdAt: string
  durationMs?: null | number
  event: LogEvent
  id: number | string
  level: LogLevel
  message: string
}

export type RunTrigger = 'clock' | 'manual' | 'runner'

export type RunSummary = {
  completed: number
  durationMs: number
  failed: number
  ran: number
  retried: number
  startedAt: string
  trigger: RunTrigger
  user?: null | string
}

export type RunLock = { token: string; until: string; user?: null | string } | null

export type SchedulerStatus = {
  lastPurgeAt?: null | string
  lastRun?: null | RunSummary
  lastSweepAt?: null | string
  lastTickAt?: null | string
  runLockToken?: null | string
  runLockUntil?: null | string
  runLockUser?: null | string
}

export type ScheduleOptions = {
  group?: string
  priority?: number
  queue?: string
  /** Join the caller's transaction. */
  req?: PayloadRequest
  scheduleAt?: Date | number | string
  unique?: boolean
}

export type RecurringOptions = ScheduleOptions & { every: Duration; startAt?: Date | number | string }
export type CronOptions = ScheduleOptions & { cron: string; startAt?: Date | number | string; tz?: string }

export type Match<S extends string = string> = { args?: ActionArgs<S>; group?: string }

export type ScheduledActionRef = {
  created: boolean
  id: number | string
  scheduleAt: Date
}

export type FindActionsArgs = {
  group?: string
  hook?: string
  limit?: number
  page?: number
  sort?: string
  status?: ActionStatus | ActionStatus[]
  where?: Record<string, unknown>
}

export type RunQueueArgs = {
  limit?: number
  maxDurationMs?: number
  queue?: string
  req?: PayloadRequest
  trigger?: RunTrigger
  user?: null | string
}

export type RunQueueResult = RunSummary & { lockedBy?: RunLock }

export type SchedulerAPI = {
  cancel: <S extends ActionSlug>(hook: S, match?: Match<S>) => Promise<number>
  cancelAll: <S extends ActionSlug>(hook: S, match?: Match<S>) => Promise<number>
  cancelByID: (id: number | string, opts?: { user?: null | string }) => Promise<boolean>
  cron: <S extends ActionSlug>(hook: S, args: ActionArgs<S>, opts: CronOptions) => Promise<ScheduledActionRef>
  enqueue: <S extends ActionSlug>(hook: S, args: ActionArgs<S>, opts?: Omit<ScheduleOptions, 'scheduleAt'>) => Promise<ScheduledActionRef>
  find: (args?: FindActionsArgs) => Promise<{ docs: ScheduledAction[]; totalDocs: number; page: number; totalPages: number }>
  has: <S extends ActionSlug>(hook: S, match?: Match<S>) => Promise<boolean>
  next: <S extends ActionSlug>(hook: S, match?: Match<S>) => Promise<'running' | Date | null>
  recurring: <S extends ActionSlug>(hook: S, args: ActionArgs<S>, opts: RecurringOptions) => Promise<ScheduledActionRef>
  reschedule: (id: number | string, scheduleAt: Date | number | string) => Promise<boolean>
  retry: (id: number | string, opts?: { runNow?: boolean }) => Promise<boolean>
  runNow: (id: number | string) => Promise<boolean>
  runQueue: (args?: RunQueueArgs) => Promise<RunQueueResult>
  schedule: <S extends ActionSlug>(hook: S, args: ActionArgs<S>, opts?: ScheduleOptions) => Promise<ScheduledActionRef>
  /** Recurring series only: finish the current occurrence, then cancel. */
  stopAfterCurrent: (id: number | string) => Promise<boolean>
}

export type RecurringSeries = {
  args?: Record<string, unknown>
  cron?: string
  every?: Duration
  group?: string
  hook: string
  key: string
  priority?: number
  tz?: string
}

export type ActionSchedulerOptions = {
  /** Endpoint and admin access. Default: any authenticated admin user. */
  access?: { create?: Access; manage?: Access; read?: Access; runQueue?: Access }
  actions: ActionDefinition<any>[]
  admin?: { dashboardWidget?: boolean; group?: string; hidden?: boolean }
  collectionSlug?: string
  defaultBackoff?: Backoff
  defaultRetries?: number
  defaultTimeout?: Duration
  defaultTimezone?: string
  /** Keep collections for migrations; no execution and API calls throw. */
  disabled?: boolean
  dispatchHorizon?: Duration
  logs?: false | { perAction?: number; slug?: string }
  maxArgsBytes?: number
  recurring?: RecurringSeries[]
  /** Scrub error text before it is stored. */
  redactError?: (error: unknown) => { message: string; stack?: string }
  retention?: { canceled?: Duration | false; complete?: Duration | false; failed?: Duration | false }
  runner?: { runQueueLimit?: number; runQueueMaxDuration?: Duration; warnAfter?: Duration }
  statusSlug?: string
  tick?: false | { cron?: string; queue?: string }
}

export type SanitizedActionSchedulerOptions = {
  access: Required<NonNullable<ActionSchedulerOptions['access']>>
  admin: { dashboardWidget: boolean; group: string; hidden: boolean }
  collectionSlug: string
  defaultBackoff: Backoff
  defaultRetries: number
  defaultTimeoutMs: number
  defaultTimezone: string
  definitions: Map<string, ActionDefinition<any>>
  disabled: boolean
  dispatchHorizonMs: number
  logs: false | { perAction: number; slug: string }
  logsSlug: null | string
  maxArgsBytes: number
  recurring: RecurringSeries[]
  redactError?: (error: unknown) => { message: string; stack?: string }
  retentionMs: { canceled: false | number; complete: false | number; failed: false | number }
  runner: { runQueueLimit: number; runQueueMaxDurationMs: number; warnAfterMs: number }
  statusSlug: string
  tick: false | { cron: string; queue: string }
}

export const RUN_TASK_SLUG = 'scheduler:run'
export const TICK_TASK_SLUG = 'scheduler:tick'
export const COMPONENT_PREFIX = '@payload-solutions/plugin-action-scheduler'

declare module 'payload' {
  export interface BasePayload {
    scheduler: SchedulerAPI
  }
}
