import type { JSONSchema4 } from 'json-schema'
import type { Config } from 'payload'

import { fieldsToJSONSchema, flattenAllFields } from 'payload'

import type { SanitizedActionSchedulerOptions } from '../types.js'

type SchemaHook = NonNullable<NonNullable<Config['typescript']>['schema']>[number]

export function interfaceNameFor(slug: string): string {
  return `ScheduledAction${slug
    .split(/[^a-z0-9]+/i)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join('')}`
}

/**
 * Adds `Config['scheduledActions']` to the generated types: one interface per action with `input`
 * built from `inputSchema`, the same way Payload types jobs tasks. Actions without an `inputSchema`
 * accept any JSON object.
 */
export function createSchedulerTypeScriptSchema(options: SanitizedActionSchedulerOptions): SchemaHook {
  return ({ collectionIDFieldTypes, config, i18n, jsonSchema }) => {
    const definitions = new Map<string, JSONSchema4>()
    const properties: Record<string, JSONSchema4> = {}

    for (const definition of options.definitions.values()) {
      const name = interfaceNameFor(definition.slug)
      let input: JSONSchema4
      if (definition.inputSchema && definition.inputSchema.length) {
        const generated = fieldsToJSONSchema(collectionIDFieldTypes, flattenAllFields({ fields: definition.inputSchema }), definitions, config, i18n)
        input = { type: 'object', additionalProperties: false, properties: generated.properties ?? {}, required: generated.required ?? [] }
      } else {
        input = { type: 'object', additionalProperties: true, properties: {} }
      }
      definitions.set(name, {
        type: 'object',
        additionalProperties: false,
        description: `Generated by @payload-solutions/plugin-action-scheduler for "${definition.slug}"`,
        properties: { input },
        required: ['input'],
      })
      properties[definition.slug] = { $ref: `#/definitions/${name}` }
    }

    jsonSchema.definitions = { ...jsonSchema.definitions, ...Object.fromEntries(definitions) }
    jsonSchema.properties = {
      ...jsonSchema.properties,
      scheduledActions: {
        type: 'object',
        additionalProperties: false,
        description: 'Generated by @payload-solutions/plugin-action-scheduler',
        properties,
        required: Object.keys(properties),
      },
    }
    if (Array.isArray(jsonSchema.required) && !jsonSchema.required.includes('scheduledActions')) {
      jsonSchema.required.push('scheduledActions')
    }
    return jsonSchema
  }
}
