import type { ProcessorPresetKey, ProcessorRole, TransferMechanism } from '../types.js'

export type ProcessorPreset = {
  key: ProcessorPresetKey
  name: string
  /** Contracting entity. Left empty where it depends on which regional entity you signed with. */
  legalName?: string
  role: ProcessorRole
  purpose: string
  dataCategories: string[]
  /** Where the processing happens, ISO 3166-1 alpha-2, or a region label like `EEA`. */
  country: string
  mechanism: TransferMechanism
  privacyUrl?: string
  dpaUrl?: string
  subprocessorsUrl?: string
  /** Publish on the sub-processor page and in Annex III by default. */
  subprocessor?: boolean
}

/**
 * Common vendors in a Payload application, as a starting point for the register.
 *
 * Every preset is seeded **unverified**. Legal entities and DPA links are the ones a
 * self-serve customer normally gets, but most vendors contract through regional entities
 * (Google Ireland Limited, AWS Europe, Stripe Payments Europe) and the correct one depends on
 * who *you* signed with — which is why an editor has to confirm each row against the contract.
 * `legalName` is deliberately empty where it is genuinely ambiguous rather than guessed at.
 */
export const PROCESSOR_PRESETS: Record<ProcessorPresetKey, ProcessorPreset> = {
  vercel: {
    key: 'vercel',
    name: 'Vercel',
    legalName: 'Vercel Inc.',
    role: 'processor',
    purpose: 'Application hosting, edge network and build infrastructure.',
    dataCategories: ['account', 'usage', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://vercel.com/legal/privacy-policy',
    dpaUrl: 'https://vercel.com/legal/dpa',
    subprocessorsUrl: 'https://vercel.com/legal/sub-processors',
    subprocessor: true,
  },
  aws: {
    key: 'aws',
    name: 'Amazon Web Services',
    role: 'processor',
    purpose: 'Cloud infrastructure: compute, storage and backups.',
    dataCategories: ['account', 'content', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://aws.amazon.com/privacy/',
    dpaUrl: 'https://aws.amazon.com/compliance/gdpr-center/',
    subprocessor: true,
  },
  cloudflare: {
    key: 'cloudflare',
    name: 'Cloudflare',
    legalName: 'Cloudflare, Inc.',
    role: 'processor',
    purpose: 'CDN, DNS, DDoS protection and edge caching.',
    dataCategories: ['technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://www.cloudflare.com/privacypolicy/',
    dpaUrl: 'https://www.cloudflare.com/cloudflare-customer-dpa/',
    subprocessor: true,
  },
  'mongodb-atlas': {
    key: 'mongodb-atlas',
    name: 'MongoDB Atlas',
    legalName: 'MongoDB, Inc.',
    role: 'processor',
    purpose: 'Managed database hosting.',
    dataCategories: ['account', 'content', 'billing'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://www.mongodb.com/legal/privacy-policy',
    dpaUrl: 'https://www.mongodb.com/legal/dpa',
    subprocessor: true,
  },
  neon: {
    key: 'neon',
    name: 'Neon',
    role: 'processor',
    purpose: 'Managed Postgres hosting.',
    dataCategories: ['account', 'content', 'billing'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://neon.com/privacy-policy',
    subprocessor: true,
  },
  supabase: {
    key: 'supabase',
    name: 'Supabase',
    legalName: 'Supabase, Inc.',
    role: 'processor',
    purpose: 'Managed Postgres, storage and authentication.',
    dataCategories: ['account', 'content'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://supabase.com/privacy',
    dpaUrl: 'https://supabase.com/legal/dpa',
    subprocessor: true,
  },
  railway: {
    key: 'railway',
    name: 'Railway',
    role: 'processor',
    purpose: 'Application and database hosting.',
    dataCategories: ['account', 'content', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://railway.com/legal/privacy',
    subprocessor: true,
  },
  digitalocean: {
    key: 'digitalocean',
    name: 'DigitalOcean',
    legalName: 'DigitalOcean, LLC',
    role: 'processor',
    purpose: 'Cloud infrastructure and object storage.',
    dataCategories: ['account', 'content', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://www.digitalocean.com/legal/privacy-policy',
    dpaUrl: 'https://www.digitalocean.com/legal/data-processing-agreement',
    subprocessor: true,
  },
  hetzner: {
    key: 'hetzner',
    name: 'Hetzner',
    legalName: 'Hetzner Online GmbH',
    role: 'processor',
    purpose: 'Server hosting and storage inside the EU.',
    dataCategories: ['account', 'content', 'technical'],
    country: 'DE',
    mechanism: 'none',
    privacyUrl: 'https://www.hetzner.com/legal/privacy-policy',
    subprocessor: true,
  },
  resend: {
    key: 'resend',
    name: 'Resend',
    role: 'processor',
    purpose: 'Transactional email delivery.',
    dataCategories: ['contact', 'account'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://resend.com/legal/privacy-policy',
    dpaUrl: 'https://resend.com/legal/dpa',
    subprocessor: true,
  },
  postmark: {
    key: 'postmark',
    name: 'Postmark',
    role: 'processor',
    purpose: 'Transactional email delivery.',
    dataCategories: ['contact', 'account'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://postmarkapp.com/privacy-policy',
    subprocessor: true,
  },
  sendgrid: {
    key: 'sendgrid',
    name: 'Twilio SendGrid',
    legalName: 'Twilio Inc.',
    role: 'processor',
    purpose: 'Transactional and marketing email delivery.',
    dataCategories: ['contact', 'account', 'marketing'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://www.twilio.com/en-us/legal/privacy',
    dpaUrl: 'https://www.twilio.com/en-us/legal/data-protection-addendum',
    subprocessor: true,
  },
  stripe: {
    key: 'stripe',
    name: 'Stripe',
    role: 'independent-controller',
    purpose: 'Payment processing, subscriptions and fraud prevention. Stripe acts as an independent controller for payment and anti-fraud purposes.',
    dataCategories: ['billing', 'contact', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://stripe.com/privacy',
    dpaUrl: 'https://stripe.com/legal/dpa',
    subprocessor: true,
  },
  paddle: {
    key: 'paddle',
    name: 'Paddle',
    legalName: 'Paddle.com Market Limited',
    role: 'independent-controller',
    purpose: 'Merchant of record: payment processing, tax and invoicing. Paddle is the seller of record and an independent controller.',
    dataCategories: ['billing', 'contact'],
    country: 'GB',
    mechanism: 'adequacy',
    privacyUrl: 'https://www.paddle.com/legal/privacy',
    dpaUrl: 'https://www.paddle.com/legal/dpa',
    subprocessor: true,
  },
  sentry: {
    key: 'sentry',
    name: 'Sentry',
    legalName: 'Functional Software, Inc.',
    role: 'processor',
    purpose: 'Error monitoring and performance tracing.',
    dataCategories: ['account', 'technical', 'usage'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://sentry.io/privacy/',
    dpaUrl: 'https://sentry.io/legal/dpa/',
    subprocessorsUrl: 'https://sentry.io/legal/subprocessors/',
    subprocessor: true,
  },
  posthog: {
    key: 'posthog',
    name: 'PostHog',
    legalName: 'PostHog Inc.',
    role: 'processor',
    purpose: 'Product analytics and session data, only where analytics consent is given.',
    dataCategories: ['usage', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://posthog.com/privacy',
    dpaUrl: 'https://posthog.com/dpa',
    subprocessorsUrl: 'https://posthog.com/subprocessors',
    subprocessor: true,
  },
  'posthog-eu': {
    key: 'posthog-eu',
    name: 'PostHog (EU Cloud)',
    legalName: 'PostHog Inc.',
    role: 'processor',
    purpose: 'Product analytics hosted in the EU, only where analytics consent is given.',
    dataCategories: ['usage', 'technical'],
    country: 'DE',
    mechanism: 'scc',
    privacyUrl: 'https://posthog.com/privacy',
    dpaUrl: 'https://posthog.com/dpa',
    subprocessorsUrl: 'https://posthog.com/subprocessors',
    subprocessor: true,
  },
  ga4: {
    key: 'ga4',
    name: 'Google Analytics 4',
    role: 'processor',
    purpose: 'Web analytics, only where analytics consent is given.',
    dataCategories: ['usage', 'technical'],
    country: 'US',
    mechanism: 'dpf',
    privacyUrl: 'https://policies.google.com/privacy',
    dpaUrl: 'https://business.safety.google/adsprocessorterms/',
    subprocessor: false,
  },
  'google-workspace': {
    key: 'google-workspace',
    name: 'Google Workspace',
    role: 'processor',
    purpose: 'Company email, documents and calendars used to run the business.',
    dataCategories: ['contact', 'content', 'support'],
    country: 'US',
    mechanism: 'dpf',
    privacyUrl: 'https://policies.google.com/privacy',
    dpaUrl: 'https://cloud.google.com/terms/data-processing-addendum',
    subprocessor: true,
  },
  intercom: {
    key: 'intercom',
    name: 'Intercom',
    role: 'processor',
    purpose: 'Customer messaging and support conversations.',
    dataCategories: ['contact', 'account', 'support'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://www.intercom.com/legal/privacy',
    dpaUrl: 'https://www.intercom.com/legal/data-processing-agreement',
    subprocessor: true,
  },
  crisp: {
    key: 'crisp',
    name: 'Crisp',
    legalName: 'Crisp IM SAS',
    role: 'processor',
    purpose: 'Live chat and support conversations.',
    dataCategories: ['contact', 'support'],
    country: 'FR',
    mechanism: 'none',
    privacyUrl: 'https://crisp.chat/en/privacy/',
    subprocessor: true,
  },
  slack: {
    key: 'slack',
    name: 'Slack',
    role: 'processor',
    purpose: 'Internal communication, including support escalations.',
    dataCategories: ['contact', 'support'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://slack.com/trust/privacy/privacy-policy',
    subprocessor: false,
  },
  openai: {
    key: 'openai',
    name: 'OpenAI',
    role: 'processor',
    purpose: 'Model inference for in-product AI features. API data is not used for training.',
    dataCategories: ['content', 'account'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://openai.com/policies/privacy-policy',
    dpaUrl: 'https://openai.com/policies/data-processing-addendum',
    subprocessor: true,
  },
  anthropic: {
    key: 'anthropic',
    name: 'Anthropic',
    legalName: 'Anthropic PBC',
    role: 'processor',
    purpose: 'Model inference for in-product AI features. API data is not used for training.',
    dataCategories: ['content', 'account'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://www.anthropic.com/legal/privacy',
    subprocessor: true,
  },
  uploadthing: {
    key: 'uploadthing',
    name: 'UploadThing',
    role: 'processor',
    purpose: 'File upload handling and storage.',
    dataCategories: ['content'],
    country: 'US',
    mechanism: 'scc',
    subprocessor: true,
  },
  cloudinary: {
    key: 'cloudinary',
    name: 'Cloudinary',
    legalName: 'Cloudinary Ltd.',
    role: 'processor',
    purpose: 'Media storage, transformation and delivery.',
    dataCategories: ['content'],
    country: 'IL',
    mechanism: 'adequacy',
    privacyUrl: 'https://cloudinary.com/privacy',
    dpaUrl: 'https://cloudinary.com/legal/data-processing-addendum',
    subprocessor: true,
  },
  'better-stack': {
    key: 'better-stack',
    name: 'Better Stack',
    role: 'processor',
    purpose: 'Uptime monitoring and log management.',
    dataCategories: ['technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://betterstack.com/privacy',
    subprocessor: true,
  },
  github: {
    key: 'github',
    name: 'GitHub',
    legalName: 'GitHub, Inc.',
    role: 'processor',
    purpose: 'Source control and CI. Reaches personal data only through issue reports and build logs.',
    dataCategories: ['contact', 'technical'],
    country: 'US',
    mechanism: 'scc',
    privacyUrl: 'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement',
    dpaUrl: 'https://github.com/customer-terms/github-data-protection-agreement',
    subprocessor: false,
  },
}
